POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "4",
    "author": "autorius",
    "url": "www.google.com",
    "userId": "5ed13d299064b708e026f98f",
    "likes": 0
}
